[project]
name = "uv-scanpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alphashape>=1.3.1",
    "ipykernel>=6.29.5",
    "scanpy>=1.11.0",
    "scikit-image>=0.25.2",
]
